var _resource_not_found_exception_8java =
[
    [ "com.chapter.monolith.DoctorRatingApp.exceptions.ResourceNotFoundException", "classcom_1_1chapter_1_1monolith_1_1_doctor_rating_app_1_1exceptions_1_1_resource_not_found_exception.html", "classcom_1_1chapter_1_1monolith_1_1_doctor_rating_app_1_1exceptions_1_1_resource_not_found_exception" ]
];