@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.chapter.monolith.DoctorRatingApp.services.DoctorServiceImpl#getDoctor(String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.chapter.monolith.DoctorRatingApp.services.DoctorServiceImpl",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_739015757 { 
   	label=chapter
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1062846101 { 
   	label=monolith
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1187496197 { 
   	label=DoctorServiceImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   DoctorServiceImpl1331149939XXXgetDoctor1808118735[
	label="+ getDoctor()"
	style=filled
	fillcolor=white
	tooltip="DoctorServiceImpl

&#10;  Retrieves a doctor by their ID from the doctor repository.&#10; &#10;  @param id The ID of the doctor to retrieve.&#10;  @return The doctor with the specified ID.&#10;  @throws NoSuchElementException if no doctor with the specified ID is found.&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1501755015 { 
   	label=DoctorController
	labeljust=l
	fillcolor=white
	style=filled
   
   DoctorController1067806754XXXgetDoctor1808118735[
	label="+ getDoctor()"
	style=filled
	fillcolor=white
	tooltip="DoctorController

&#10;  Retrieves the details of a doctor with the given doctorId.&#10; &#10;  @param doctorId The unique identifier of the doctor.&#10;  @return A ResponseEntity containing the doctor details if found, or an empty body with an appropriate status code if not found.&#10; "
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
DoctorController1067806754XXXgetDoctor1808118735 -> DoctorServiceImpl1331149939XXXgetDoctor1808118735;
    
}
@enduml