@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.chapter.monolith.DoctorRatingApp.controllers.RatingController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_739015757 { 
   	label=chapter
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1062846101 { 
   	label=monolith
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   RatingController1067806754[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RatingController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ratingService: RatingService [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createRating(rating: Rating): ResponseEntity&lt;Rating&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllRatingByDoctorId(doctorId: String): ResponseEntity&lt;List&lt;Rating&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllRatingByUserId(userId: String): ResponseEntity&lt;List&lt;Rating&gt;&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RatingServiceImpl1331149939[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RatingServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ratingRepository: RatingRepository [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getAllRatingByDoctor(id: String): List&lt;Rating&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllRatingByUser(id: String): List&lt;Rating&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveRating(rating: Rating): Rating</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
RatingController1067806754 -> RatingServiceImpl1331149939[arrowhead=none];
    
}
@enduml